[2024-05-10T08:22:24.311+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T08:22:24.331+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: file_process_dag.process_file manual__2024-05-10T08:22:23.708738+00:00 [queued]>
[2024-05-10T08:22:24.338+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: file_process_dag.process_file manual__2024-05-10T08:22:23.708738+00:00 [queued]>
[2024-05-10T08:22:24.339+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-10T08:22:24.364+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_file> on 2024-05-10 08:22:23.708738+00:00
[2024-05-10T08:22:24.369+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T08:22:24.370+0000] {standard_task_runner.py:63} INFO - Started process 125 to run task
[2024-05-10T08:22:24.371+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'file_process_dag', 'process_file', 'manual__2024-05-10T08:22:23.708738+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/from_folder_to_other.py', '--cfg-path', '/tmp/tmpnfvdgnm7']
[2024-05-10T08:22:24.373+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask process_file
[2024-05-10T08:22:24.419+0000] {task_command.py:426} INFO - Running <TaskInstance: file_process_dag.process_file manual__2024-05-10T08:22:23.708738+00:00 [running]> on host 24b77fb676b2
[2024-05-10T08:22:24.518+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='file_process_dag' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T08:22:23.708738+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T08:22:23.708738+00:00'
[2024-05-10T08:22:24.519+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T08:22:24.531+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T08:22:24.531+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/from_folder_to_other.py", line 17, in process_file
    dest_file = os.path_join(dest_folder, filename)
                ^^^^^^^^^^^^
AttributeError: module 'os' has no attribute 'path_join'
[2024-05-10T08:22:24.547+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=file_process_dag, task_id=process_file, execution_date=20240510T082223, start_date=20240510T082224, end_date=20240510T082224
[2024-05-10T08:22:24.564+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task process_file (module 'os' has no attribute 'path_join'; 125)
[2024-05-10T08:22:24.587+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T08:22:24.601+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T08:22:24.608+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
